name: validate-json-yaml-format
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v3.2.1
        #with:
        #  exclude_file: exclude.txt
        #  json_schema: schema.json # validate JSON files against the schema
